### ISSUE TITLE
Eliminate dropout?

### ISSUE THREAD

**Issue by AndreaPisoni** [amir-abdi/keras_to_tensorflow#1]
Hi Amir!!

Great job with the library. One thing that might be an issue sometimes however is the dropout handling. For example, you might want to freeze the graph to deploy the .pb file in iOS/Android, which means you have to remove the dropout nodes (or get a op RandomUniform not supported error...), however, in Keras the variables at inference time (Trainable=False) get rescaled to account for the fact that now all the nodes are active. 

So how do you handle the dropout when you freeze your keras model to tensor flow?

**Comment by thomasjungblut** [comment]
The trick is that you have to set 

`K.set_learning_phase(0)`

before exporting the graph, that will eliminate the dropout layers effectively.

**Comment by amir-abdi** [comment]
`K.set_learning_phase(0)` to solve the dropout issue among other issues.

**Comment by 13301338176** [comment]
K.set_learning_phase(0) will not work

**Comment by scipioni** [comment]
Confirm that K.set_learning_phase(0) does not eliminate dropout nodes from graph. Anyone exported keras model to opencv dnn ?
