### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by MatthewScholefield** [amir-abdi/keras_to_tensorflow#10]
If you get a chance, could you add a license file to the repo? Thanks!

**Comment by amir-abdi** [comment]
The license is now added.

**Comment by MatthewScholefield** [comment]
Nooo, GPL xD. Oh well.

**Comment by amir-abdi** [comment]
No worries, changed it to MIT.
Feel free to use it without disclosing the source.

**Comment by MatthewScholefield** [comment]
Thanks a bunch!
