### ISSUE TITLE
Can not convert the H5 model to tensorflow Pb model

### ISSUE THREAD

**Issue by denghuiru** [amir-abdi/keras_to_tensorflow#11]
@amir-abdi
Hi, very thanks to your reply about my problems!
I use the code exactly the same with you and my problem is also that can not convert the H5 model to tensorflow model.
In the code "net_model = load_model(weight_file_path)", error happens, and the error info is 
"raise ValueError('No model found in config file.')"

**Comment by amir-abdi** [comment]
Can you paste your code here?

**Comment by denghuiru** [comment]
@amir-abdi
The code i use is as follows, actually just the code of you provided, and I made no modification of your code:
input_fld = './keras_to_tensorflow-master'
weight_file = 'model.h5'
num_output = 1
write_graph_def_ascii_flag = True
prefix_output_node_names_of_final_network = 'output_node'
output_graph_name = 'new_model.pb'
weight_file_path = osp.join(input_fld, weight_file)
K.set_learning_phase(0)
net_model = load_model(weight_file_path)
However, the code errors in the line of "net_model = load_model(weight_file_path)", error information is just as above.

**Comment by amir-abdi** [comment]
Are you sure that `model.h5` is inside the folder `keras_to_tensorflow-master`?
If you are running the code from the root of the cloned repository, and the model is in the root of the repository, you should set `input_fld = '.'`

**Comment by denghuiru** [comment]
@amir-abdi
Yes, the model.h5 is in the keras_to_tensorflow-master file, and the "input_fld" I have also tried '.' and absoult path, the results are all error when running to the "net_model = load_model(weight_file_path)" line,

**Comment by amir-abdi** [comment]
I have no other hypothesis:
- Either the file address is wrong,
- Or you have not saved the model correctly.

**Comment by amir-abdi** [comment]
@denghuiru Try the new python implementation where you can just run it with correct arguments (see README for this).

**Comment by amir-abdi** [comment]
@denghuiru 
I assume your issue is resolved.
Please reopen otherwise.
