### ISSUE TITLE
Bug and bugfix for convertion to tensorflow

### ISSUE THREAD

**Issue by tsenst** [amir-abdi/keras_to_tensorflow#12]
While freezing the MINT net i recognized a small bug which lead to a wrong results when running the network in forward mode. With the current version the output has been  connected in a wrong manner. The current code I am adressing is:
```
K.set_learning_phase(0)
net_model = load_model(weight_file_path)

pred = [None]*num_output
pred_node_names = [None]*num_output
for i in range(num_output):
     pred_node_names[i] = prefix_output_node_names_of_final_network+str(i)
     pred[i] = tf.identity(net_model.output[i], name=pred_node_names[i]),
print('output nodes names are: ', pred_node_names)
```
It seams that there is a small typo in `net_model.output[i]`. If the output**s** field is used instead (`net_model.outputs[i]`) everythink works fine for me. I. e. the fix will be:
```
K.set_learning_phase(0)
net_model = load_model(weight_file_path)

pred = [None]*num_output
pred_node_names = [None]*num_output
for i in range(num_output):
     pred_node_names[i] = prefix_output_node_names_of_final_network+str(i)
     pred[i] = tf.identity(net_model.outputs[i], name=pred_node_names[i]),
print('output nodes names are: ', pred_node_names)
```

**Comment by amir-abdi** [comment]
@tsenst I never encountered any differences using model.output vs model.outputs (but it was a white back since I tried the conversion with multiple outputs). So, I had assumed that both functions point to the same end-point. Regardless, your suggestion is valid and the code is updated accordingly.
Thanks.
