### ISSUE TITLE
I can not convert the keras - mask rcnn.h5 model to tensorflow Pb model ,thanks.

### ISSUE THREAD

**Issue by maxlchina** [amir-abdi/keras_to_tensorflow#18]
Traceback (most recent call last):
  File "/home/maxl/DeepLearning/Mask_RCNN-master/export_keras_to_tensorflow.py", line 51, in <module>
    net_model = load_model(weight_file_path)
  File "/home/maxl/anaconda3/lib/python3.5/site-packages/keras/models.py", line 237, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

**Comment by amir-abdi** [comment]
What is the `weight_file_path` is pointing to? Have you set it to your saved model?

**Comment by zhudaoruyi** [comment]
@maxlchina 权重文件不行的，必须要带有网络结构。就是说，被转换的h5文件应该是 keras中的 model.save()，而不是model.save_weights()

**Comment by Surmeh** [comment]
I'm facing the same issue.

**Comment by amir-abdi** [comment]
`weight_file_path = osp.join(args.input_fld, args.input_model_file)`
So, what have you set as the `input_fld` and `input_model_file` arguments?

**Comment by Surmeh** [comment]
This is what I've changed in the python file. The command used is:
python keras_to_tensorflow.py -input_model_file mask_rcnn_coco.h5 -output_model_file mask_rcnn_coco.pb
-----------------------------------------------------------------------------------------------
import argparse
parser = argparse.ArgumentParser(description='set input arguments')
parser.add_argument('-input_fld', action="store", 
                    dest='input_fld', type=str, default='/home/surabhi/Tensorflow_Models')

parser.add_argument('-output_fld', action="store", 
                    dest='output_fld', type=str, default='/home/surabhi/Tensorflow_Models')

parser.add_argument('-input_model_file', action="store", 
                    dest='input_model_file', type=str, default='model.h5')

parser.add_argument('-output_model_file', action="store", 
                    dest='output_model_file', type=str, default='model.pb')
-------------------------------------------------------------------------------------------------------
**Output of the command** 
(Pdb) weight_file_path
'/home/surabhi/Tensorflow_Models/mask_rcnn_coco.h5'

**Comment by amir-abdi** [comment]
I'm kind of curious whether you have made any changes to the remaining code. For example, the first `print` code is `print('input args: ', args)` which is supposed to print out the input arguments. But I don't see this as part of the `output of the command` you have entered.

Do you mind pasting your entire revised implementation?
You can also send me your trained model, if you like, and I will try to convert it to see if the bug you are reporting is reproducible.

**Comment by Surmeh** [comment]
I do get the input_args output, thought you just wanted the weight_file_path output, so pasted that. This is full output: 
[mask_rcnn_keras_to_tensorflow.txt](https://github.com/amir-abdi/keras_to_tensorflow/files/1685700/mask_rcnn_keras_to_tensorflow.txt)
('input args: ', Namespace(f=None, graph_def=False, input_fld='/home/surabhi/Tensorflow_Models', input_model_file='mask_rcnn_coco.h5', num_outputs=1, output_fld='/home/surabhi/Tensorflow_Models', output_graphdef_file='model.ascii', output_model_file='mask_rcnn_coco.pb', output_node_prefix='output_node'))
/home/surabhi/tensorflow/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 94, in <module>
    net_model = load_model(weight_file_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 241, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

I've attached the revised code herein. I've got the mask_rcnn_coco.h5 from https://github.com/matterport/Mask_RCNN/releases. Thanks for alll your help.

**Comment by amir-abdi** [comment]
@Surmeh 
From my understanding, the problem is that when you saved the file, you only saved the weights and not the model. Or maybe you are downloading pretrained weights for a given model. If that is the case, you first need to load the model and then load its weights, with a code like follows:

```
def create_model():
    model = Sequential()
    ....
    return model

model = create_model()
model.load_weights(weights_path)
```

However, if you had stored the complete model (definition + weights), you could load it using `load_model`.

See this thread on stackoverflow: https://stackoverflow.com/questions/35074549/how-to-load-a-model-from-an-hdf5-file-in-keras

**Comment by mengxiabing** [comment]
@amir-abdi ValueError: Unknown layer: BatchNorm

**Comment by cuimiao187561** [comment]
Can you solve this problem? I am facing the same problem @zhudaoruyi
