### ISSUE TITLE
Redundant output_node_names_of_input_network?

### ISSUE THREAD

**Issue by lmsasu** [amir-abdi/keras_to_tensorflow#2]
Hello Amir,

I wonder whether the` output_node_names_of_input_network` is not redundant: couldn't we consider just `net_model.output.name` from the model loaded as `load_model(weight_file_path)`?

**Comment by amir-abdi** [comment]
Good catch lmasasu. Fixed the issue, to only set the num_output variable. Not sure if I can trust to get len(net_model.output) instead; will check and might update the code again.
