### ISSUE TITLE
Cannot convert a Resnet model created with Keras (Thaeno backend) to tensorflow

### ISSUE THREAD

**Issue by AswathKiruba** [amir-abdi/keras_to_tensorflow#21]
Hi Amir, 
            Thanks for sharing your code. I am trying to convert Resnet model(h5 file) created using Thaeno backend to a tensorflow (pb file). I tried your code, but it threw an error stating, "Dimension 1 in both shapes must be equal, but are 32 and 64 for 'merge_1_9/concat".

 I was able to figure out that Theano and TensorFlow implement convolution in different ways, and thus, convolution filters trained with Theano need to be converted before being with TensorFlow.

 Is there any way to implement the conversion of Keras(Thaeno) to tensorflow. Thanks in advance.

**Comment by AswathKiruba** [comment]
Amir. I was able to solve it. Just we need to add 

K.set_image_data_format('channels_first')  after the line K.set_learning_phase(0).

Thanks once again.

**Comment by amir-abdi** [comment]
@AswathKiruba 
That sounds good.
Feel free to send a pull request with the new feature.
