### ISSUE TITLE
Converting the from Keras h5 model to checkpoint/meta tensorflow format

### ISSUE THREAD

**Issue by AswathKiruba** [amir-abdi/keras_to_tensorflow#23]
Hi Amir,
             Can we do the enhancement of converting the Keras h5 model to tensorflow format of checkpoint/meta?

**Comment by AswathKiruba** [comment]
#29 
Hi Amir,
           I have converted the Keras model to meta and check point. Thank you.

**Comment by tuji-sjp** [comment]
Hello, could you tell me how to convert the Keras model to Tensorflow model with (.meta, checkpoint) format? I still don't know how to do it.

**Comment by tuji-sjp** [comment]
> #29
> 嗨埃米尔
> 我已经将Keras模型转换为元和检查点。谢谢。

hello? Can you see my question?

**Comment by tuji-sjp** [comment]
> #29
> Hi Amir,
> I have converted the Keras model to meta and check point. Thank you.

hello? Can you see my question?
