### ISSUE TITLE
what is tf.identify for

### ISSUE THREAD

**Issue by wweichn** [amir-abdi/keras_to_tensorflow#3]
Thanks for your work.
I wonder the meaning of tf.identify(model.output,pred_output_name).
Does it mean add the output node of the original keras model to the new Tf model, and give it a name?
Then the problem is the size of output num. If the shape of output of my keras model is (?,5)
,  ? represents batchsize,5 represents the columns of the output. The  output is a list, then how do I set the value of.num_output?
Is any value ok? Does it depends on the batchsize I want to set?

**Comment by amir-abdi** [comment]
Using the `tf.identity` was my way of renaming the output node to something I desire for later use. `tf.identity` return a tensor with the same shape and contents as the input tensor or value.
You don't need to worry about the shape of your output. Using tf.identity will preserve the shape.

Your batch size is a different story than network design.

**Comment by wweichn** [comment]
ok，I have worked it out. Thank you.
