### ISSUE TITLE
Getting error with weight_file_path and relu 6

### ISSUE THREAD

**Issue by suranakritika** [amir-abdi/keras_to_tensorflow#31]
The error says "ValueError: Unknown activation function: relu6" 
and even getting error with weights file it says 

ValueError                                Traceback (most recent call last)
<ipython-input-8-f1ef159e5345> in <module>()
     15     Check the keras documentation for more details (https://keras.io/getting-started/faq/)'''
     16           .format(weight_file_path))
---> 17     raise err
     18 num_output = args.num_outputs
     19 pred = [None]*num_output

**Comment by amir-abdi** [comment]
@suranakritika 
Check this thread on keras about `CustomObjectScope`:
https://github.com/keras-team/keras/issues/7431
