### ISSUE TITLE
The following error occurred

### ISSUE THREAD

**Issue by liangbo-1** [amir-abdi/keras_to_tensorflow#32]
``Traceback (most recent call last):
  File "pb1.py", line 110, in <module>
    raise err
  File "pb1.py", line 101, in <module>
    net_model = load_model(weight_file_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 241, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

**Comment by amir-abdi** [comment]
@liangbo-1 
Based on the error you are reporting, it seems as if the `.h5` file you are referring to as the model weight file does not contain the model description.

Try saving your network configuration and its weights with the following code snippet:
` model.save('my_filename'),`

**Comment by cuimiao187561** [comment]
Can you solve this problem? I am facing the same problem @liangbo-1
