### ISSUE TITLE
Is it feasible to quantize a model, and convert it back to a keras model?

### ISSUE THREAD

**Issue by ophiry** [amir-abdi/keras_to_tensorflow#34]

**Comment by amir-abdi** [comment]
At this point, I am not even sure if the "quantization" feature of TF is working in the conversion process. I have not tried to convert it back, but if you read the [quantization documentation of tensorflow ](https://www.tensorflow.org/performance/quantization), you might agree with me that this feature is tensorflow specific. From my understanding, keras has not implemented such feature.

**Comment by amir-abdi** [comment]
@ophiry Feel free to reopen this issue in case you found your suggestion feasible. We can then figure out "how" to do it.
