### ISSUE TITLE
Unknown loss function:<lambda>

### ISSUE THREAD

**Issue by linhqhta** [amir-abdi/keras_to_tensorflow#46]
@amir-abdi : Thank you for your great work,
I have a problem when converting mymodel.h5 to mymodel.pb

Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 123, in <module>
    raise err
  File "keras_to_tensorflow.py", line 114, in <module>
    net_model = load_model(weight_file_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 274, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 626, in compile
    loss_functions.append(losses.get(loss.get(name)))
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 122, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 164, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:<lambda>

Have you any suggestion to solve this?
Thanks,

**Comment by jma100** [comment]
In your line 114, change load_model(weight_file_path) to net_model = load_model(weight_file_path, custom_objects={'YOUR_LOSS_FUNCTION' : YOUR_LOSS_FUNCTION })

You probably used a custom loss function instead of keras built-ins. Just need to give the loss function you are using.

**Comment by linhqhta** [comment]
> @linhqhta Do you have a solution to this problem?

I have solved this problem by re-compiling my model using build-in keras loss function (mse)

**Comment by szuRyan** [comment]
@linhqhta thank you for your answer. I use the ctc loss function. Since lamdba is used to enter multiple parameters, the unknown loss function will appear. Is this (mse) mean square error?

**Comment by linhqhta** [comment]
Because loss function only used for training, not for predicting, then I re-complied my loss function (ctc) to keras build-in loss function (mse) and this code (keras_to_tensorflow.py) run well :)

**Comment by szuRyan** [comment]
Thank you very much for your answer. Just getting started with keras, learning with an open mind, Can you give me a demo about this part?

**Comment by szuRyan** [comment]
@linhqhta Thank you very much for your answer. Just getting started with keras, learning with an open mind, Can you give me a demo about this part?

**Comment by linhqhta** [comment]
Modify some line in **keras_to_tensorflow.py** file like below then using it to convert *.h5 to *.pb

try:
    **net_model = load_model(weight_file_path, compile=False)
    net_model.compile(loss='mse', optimizer='sgd')**
    
except ValueError as err:
    print('''Input file specified ({}) only holds the weights, and not the model defenition.
    Save the model using mode.save(filename.h5) which will contain the network architecture
    as well as its weights. 
    If the model is saved using model.save_weights(filename.h5), the model architecture is 
    expected to be saved separately in a json format and loaded prior to loading the weights.
    Check the keras documentation for more details (https://keras.io/getting-started/faq/)'''
          .format(weight_file_path))
    raise err

**Comment by zhong110020** [comment]
> @linhqhta thank you for your answer. I use the ctc loss function. Since lamdba is used to enter multiple parameters, the unknown loss function will appear. Is this (mse) mean square error?

I have the same error, please help!
