### ISSUE TITLE
the graph is empty

### ISSUE THREAD

**Issue by RMobina** [amir-abdi/keras_to_tensorflow#49]
hi,
I created the .pb file from .h5 (when I tried to convert hdf5 to .pb I receive below error) but when I can not show the graph on the tensorboard because it's empty. could you please guide me.

 return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'input_dtype'
Best

**Comment by amir-abdi** [comment]
Sorry for the late response, but the tool is not updated which hopefully resolves your issue.
