### ISSUE TITLE
Error regarding load_model and set_learning_phase order

### ISSUE THREAD

**Issue by davVision** [amir-abdi/keras_to_tensorflow#5]
When I execute your script I successfully obtain the .pb file however, when using it in C++, I get following error:

```
> 2017-07-12 11:45:15.158206: W D:\Tensorflow\tensorflow\tensorflow\core\framework\op_kernel.cc:1191] Invalid argument: You must feed a value for placeholder tensor 'keras_learning_phase' with dtype bool
>          [[Node: keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

By changing the order of **load_model** and **set_learning_phase**, i.e,

```
K.set_learning_phase(0)
net_model = load_model(weight_file_path)
```

the inference works smoothly.

I have a further question:
I would like to execute the graph with batchsize greater than 1. I figured out that by increasing **num_output** (let's say, 2) it would make the trick. But it did not work.

Do you have any idea of what to do to increase the batchsize?

Thanks!

**Comment by amir-abdi** [comment]
Thanks for letting me know if the error in the order I had set the `learning_phase` flag.

`num_output` has nothing to do with the batchsize. 
This conversion tool is designed to work for networks with multiple inputs and multiple outputs. `num_output` defines the number of outputs in a multi-stream network (network with a forked design).

In terms of variable batchsize, maybe this tip helps (https://www.tensorflow.org/programmers_guide/faq):

> When building a variable-size graph, the most important thing to remember is not to encode the batch size as a Python constant, but instead to use a symbolic Tensor to represent it. The following tips may be useful:
>  Use batch_size = tf.shape(input)[0] to extract the batch dimension from a Tensor called input, and store it in a Tensor called batch_size.

**Comment by davVision** [comment]
Glad my observation helped and thanks for your response! ;)

 

Jaume Garcia i Barnés

Computer Vision R&D

 

 

Davantis Technologies S.L.

Edifici Eureka

08193 Bellaterra Spain

Email:  <mailto:oriol.herrera@davantis.com> jaume.garcia@davantis.com

Web:  <http://www.davantis.com/> www.davantis.com 

 

cid:image001.png@01D18370.629EDFD0

 

Este correo electrónico es privado y puede contener información confidencial. Si recibiera el mensaje por error le agradeceremos nos lo comunique, absteniéndose de difundirlo, distribuirlo, copiarlo o almacenarlo, y que lo elimine, así como cualquier documento adjunto que pudiese contener. Su dirección de correo electrónico junto a sus datos personales que facilitó se hallan incorporados en un fichero titularidad de Davantis Technologies, S.L. cuya finalidad es la de mantener el contacto con Ud. Asimismo, Ud. puede ejercer su derecho de acceso, rectificación, cancelación y oposición mediante el envío de un correo electrónico a la dirección smarterthinking@davantis.com, o mediante carta dirigida a la siguiente dirección: UAB Edificio Eureka, Bellaterra, España.

 

This email is private and may contain confidential information. If you receive this email by mistake, please be so kind to notify us, and abstain from disclosing, distributing, copying or recording it, and proceed to delete it, as well as any attachment that may contain. Your email address and other personal data disclosed by you are incorporated in a file of Davantis Technologies, S.L., which purpose is to maintain contact with you. You can exercise your access, rectification, cancellation and/or opposition rights by sending an email to the email address smarterthinking@davantis.com, or by letter addressed to: UAB Edificio Eureka, Bellaterra, Spain.

 

De: amir-abdi [mailto:notifications@github.com] 
Enviado el: Wednesday, 12 July de 2017 19:16
Para: amir-abdi/keras_to_tensorflow
CC: davVision; Author
Asunto: Re: [amir-abdi/keras_to_tensorflow] Error regarding load_model and set_learning_phase order (#5)

 

Thanks for letting me know if the error in the order I had set the learning_phase flag.

num_output has nothing to do with the batchsize.
This conversion tool is designed to work for networks with multiple inputs and multiple outputs. num_output defines the number of outputs in a multi-stream network (network with a forked design).

In terms of variable batchsize, maybe this tip helps (https://www.tensorflow.org/programmers_guide/faq):

When building a variable-size graph, the most important thing to remember is not to encode the batch size as a Python constant, but instead to use a symbolic Tensor to represent it. The following tips may be useful:
Use batch_size = tf.shape(input)[0] to extract the batch dimension from a Tensor called input, and store it in a Tensor called batch_size.
