### ISSUE TITLE
can .pb be converted to .h5 or other type?

### ISSUE THREAD

**Issue by aimhabo** [amir-abdi/keras_to_tensorflow#50]
hello!
I wanna convert a .pb to .weight(for darknet). now I find a project can convert .h5 to .weight. Are there any way to convert .pb to .h5?

**Comment by amir-abdi** [comment]
Unfortunately, this is not what the tool is intended for.

Maybe this stackoverflow thread helps: https://stackoverflow.com/questions/44466066/how-can-i-convert-a-trained-tensorflow-model-to-keras
