### ISSUE TITLE
a question about keras model output is different from converted pb output

### ISSUE THREAD

**Issue by alexliyang** [amir-abdi/keras_to_tensorflow#61]
hi:
    my model output like this:  Model(inputs=inp, outputs=out) , out is a list  : out[11].
   when I use this file to convert keras to tf pb,  output_num should be 11 or 1?
   
    another question is anyway 11 or 1,  the pb model predict output allways different from keras modle output. I don't know how to deal with it.

**Comment by amir-abdi** [comment]
I hope the new version of the tool resolves this issue for you. Otherwise, please reopen the issue.
