### ISSUE TITLE
the 'quantize' argument

### ISSUE THREAD

**Issue by phoenares** [amir-abdi/keras_to_tensorflow#62]
Hi, I tried to set 'quantize' True,
but the model doesn't become smaller and the infer time is much longer
did I do something wrong
thanks

**Comment by amir-abdi** [comment]
I have not had much luck with the quantize feature of GraphTransformation as well. But it was a cool thing to add. Report the issue on tensorflow github.

**Comment by phoenares** [comment]
thanks a lot, I will try
