### ISSUE TITLE
.pb file is larger than .h5

### ISSUE THREAD

**Issue by thilohuellmann** [amir-abdi/keras_to_tensorflow#65]
I'm trying to reduce the size of an existing .h5 model (VGG16) before using it for inference. After executing the script, the resulting .pb file is even larger than the .h5 file. Is this a behavior that can occur? I hoped the .pb file will be significantly smaller.

**Comment by jayanij** [comment]
> I'm trying to reduce the size of an existing .h5 model (VGG16) before using it for inference. After executing the script, the resulting .pb file is even larger than the .h5 file. Is this a behavior that can occur? I hoped the .pb file will be significantly smaller.

did you find a solution?

**Comment by amir-abdi** [comment]
I am not sure why the size is bigger, but I never expected it to be "significantly smaller". Please note that Keras is only a wrapper for the backends it supports (i.e. TensorFlow). So, the converted model should have relatively the same size.
