### ISSUE TITLE
Weights are wrong when converting to tensorflow

### ISSUE THREAD

**Issue by zacharynevin** [amir-abdi/keras_to_tensorflow#7]
### System Info
- OS: Ubuntu 16.04
- Tensorflow 1.2.0
- Keras 1.2.2

### Description
Hi there,

I have a model called `model.h5` that works fine in tests using Keras. *Note: the model was trained in Keras v1.2.2, not Keras v2.x*.

When I apply this script and try to run the `constant_graph_weights.pb` in tensorflow, my outputs are completely different (see code below).

The original model was made by transfer learning on the VGG-19 network. The VGG-19 weights were frozen, and the head was cut off and trained to take images and output 4 mutually exclusive categories. In Keras, this model works fine - I get 4 probabilities that add to 1.

In tensorflow, all my probabilities are roughly 0.25 no matter what. I'm thinking that the graph definition is being loaded properly but the weights aren't being applied at all - the retrained "head" of the network is probably using something like the default weights initialization.

Anyway, given the `constant_graph_weights.pb` file, here is what I use to generate the tensorflow prediction from an image, vs what I use in Keras:

```
#### TENSORFLOW ####
import tensorflow as tf
from tensorflow.python.platform import gfile
import cv2

def analyze_tf(image):
  with gfile.FastGFile('./constant_graph_weights.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    g_in = tf.import_graph_def(graph_def)

  sess = tf.Session()
  output = sess.graph.get_tensor_by_name('Softmax:0')
  input_tensor = sess.graph.get_tensor_by_name('input_1:0')
  init_op = sess.graph.get_operation_by_name('init')
  sess.run(init_op)
  pred_results = sess.run(output, {input_tensor: frame })

  return pred_results

image = cv2.imread('path/to/image')
pred = analyze_tf(normalize_image(image))
print(pred)
```

And the keras code, which works fine:
```
#### KERAS ####
from keras.models import load_model
from keras import backend
import cv2

os.environ["KERAS_BACKEND"] = "tensorflow"
backend.set_image_dim_ordering('tf')

model = load_model('./original_keras_model.h5')
def analyze_keras(image):
  return model.predict(image)

image = cv2.imread('path/to/image')
pred = analyze_keras(normalize_image(image))
print(pred)
```

Thanks so much for all your help!

**Comment by amir-abdi** [comment]
Share how you modified the conversion script to fit your needs.
