### ISSUE TITLE
Unknown layer: BilinearUpSampling2D

### ISSUE THREAD

**Issue by ZhaoPeixiao** [amir-abdi/keras_to_tensorflow#72]
Hi, I add BilinearUpSampling2D layer defined here https://github.com/aurora95/Keras-FCN/blob/master/utils/BilinearUpSampling.py and I got an ValueError:Unknown layer: BilinearUpSampling2D. How can I fix this? Besides, does your code support custom layers? Thanks!

**Comment by amir-abdi** [comment]
The code does not support custom layers. You should modify the code and include your custom layer.
