### ISSUE TITLE
Unable to convert .h5 fie to .pb file, valueError: unknown layer: InstanceNormalization

### ISSUE THREAD

**Issue by npvaddoriya** [amir-abdi/keras_to_tensorflow#87]
Hii @amir-abdi  I am facing this issue while converting .h5 file to .pb file, Can you please help me.
![Screenshot 2019-06-24 at 8 05 07 PM](https://user-images.githubusercontent.com/34957850/60073174-57011a00-973d-11e9-991a-8c394aedd234.png)

Thank you.

**Comment by amir-abdi** [comment]
You have a custom layer. Change my code and import your custom layer prior to loading the model.

**Comment by taotaoyuhust** [comment]
i got the same problem, which i used a custom layer and got the error "Unknown layer: PixelShuffler"
how to fix it ? 
i add the code "import PixelShuffler" at the top of the file but still not help
Thank you !
